exports.tens = [
  "",
  "",
  "twenty",
  "thirty",
  "forty",
  "fifty",
  "sixty",
  "seventy",
  "eighty",
  "ninety",
];

exports.units = [
  "",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
  "fourteen",
  "fifteen",
  "sixteen",
  "seventeen",
  "eighteen",
  "nineteen",
];

exports.scales = [
  "",
  "thousand",
  "million",
  "billion",
  "trillion",
  "quadrillion",
  "quintillion",
  "sextillion",
  "septillion",
  "octillion",
  "nonillion",
  "decillion",
  "undecillion",
  "duodecillion",
  "tredecillion",
  "quatttuor-decillion",
  "quindecillion",
  "sexdecillion",
  "septen-decillion",
  "octodecillion",
  "novemdecillion",
  "vigintillion",
  "centillion",
];

// For Test Case
exports.testCases = [
  [0, "Zero"],
  [1, "One"],
  [2, "Two"],
  [3, "Three"],
  [4, "Four"],
  [5, "Five"],
  [6, "Six"],
  [7, "Seven"],
  [8, "Eight"],
  [9, "Nine"],
  [10, "Ten"],
  [11, "Eleven"],
  [12, "Twelve"],
  [13, "Thirteen"],
  [14, "Fourteen"],
  [15, "Fifteen"],
  [16, "Sixteen"],
  [17, "Seventeen"],
  [18, "Eighteen"],
  [19, "Nineteen"],
  [20, "Twenty"],
  [30, "Thirty"],
  [40, "Forty"],
  [50, "Fifty"],
  [60, "Sixty"],
  [70, "Seventy"],
  [80, "Eighty"],
  [90, "Ninety"],
  [42, "Forty Two"],
  [99, "Ninety Nine"],
];
